server {
    listen 80;
    listen [::]:80;
    server_name hosseintalab.ir www.hosseintalab.ir;

    root /var/www/hosseintalab.ir/current;
    index index.html;

    error_page 404 /404.html;

    location ^~ /.well-known/acme-challenge/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location = /404.html {
        internal;
    }
}
